### ISSUE TITLE
'str' object has no attribute 'custom_ca_file

### ISSUE THREAD

**Issue by QuarantineENG** [dhs-ncats/pshtt#57] opened 2017-02-16 13:08 UTC
Traceback (most recent call last):
  File "/usr/bin/pshtt", line 9, in <module>
    load_entry_point('pshtt==0.1.5', 'console_scripts', 'pshtt')()
  File "/usr/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 873, in inspect_domains
    preload_list = create_preload_list()
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 800, in create_preload_list
    request = requests.get(file_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory
[root@secengfedora25 Desktop]# pshtt www.state.gov
Traceback (most recent call last):
  File "/usr/bin/pshtt", line 9, in <module>
    load_entry_point('pshtt==0.1.5', 'console_scripts', 'pshtt')()
  File "/usr/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 873, in inspect_domains
    preload_list = create_preload_list()
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 800, in create_preload_list
    request = requests.get(file_url)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory

thoughts?
v/r
Q

**Comment by QuarantineENG** [comment] 2017-02-16 13:26
I believe I may have fixed this by performing this command;  export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt

**Comment by QuarantineENG** [comment] 2017-02-16 13:29
Is this caused by a SSL cert issue;
COMODO ECC Domain Validation Secure Server CA 2'),))}
Traceback (most recent call last):
  File "/usr/bin/pshtt", line 9, in <module>
    load_entry_point('pshtt==0.1.5', 'console_scripts', 'pshtt')()
  File "/usr/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 882, in inspect_domains
    results.append(inspect(domain))
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 64, in inspect
    basic_check(domain.httpswww)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 173, in basic_check
    https_check(endpoint)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 331, in https_check
    cert_plugin_result = cert_plugin.process_task(server_info, 'certinfo_basic')
  File "/usr/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 115, in process_task
    if scan_command.custom_ca_file:
AttributeError: 'str' object has no attribute 'custom_ca_file'

**Comment by QuarantineENG** [comment] 2017-02-16 13:39
Here is another run at it;
Failed to connect.
Traceback (most recent call last):
  File "/usr/bin/pshtt", line 9, in <module>
    load_entry_point('pshtt==0.1.5', 'console_scripts', 'pshtt')()
  File "/usr/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 882, in inspect_domains
    results.append(inspect(domain))
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 63, in inspect
    basic_check(domain.https)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 173, in basic_check
    https_check(endpoint)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 331, in https_check
    cert_plugin_result = cert_plugin.process_task(server_info, 'certinfo_basic')
  File "/usr/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 115, in process_task
    if scan_command.custom_ca_file:
AttributeError: 'str' object has no attribute 'custom_ca_file'

**Comment by konklone** [comment] 2017-02-16 17:10
What command did you run? Can you provide us a hostname that reproduces
this?

-- Eric

**Comment by fishouttah20** [comment] 2017-02-16 17:26
I'm seeing a similar error on analytics.uk.barclays (and yes there is a mismatched cert).

**Comment by konklone** [comment] 2017-02-16 23:31
@QuarantineENG Is every single command `pshtt www.state.gov`? Are you trying other domains, other flags?

It looks like you have a strange root store situation on the box you're running this from, but I would like to handle this situation more gracefully than a stack trace.

**Comment by QuarantineENG** [comment] 2017-02-23 15:26
I have had to compile a list from our DNS dump and then some other sources. I have over 2k different URLS to check both external and internal. I am having issues with it failing when reading from the *.cvs file where I placed all of the IPs and URLs.

**Comment by h-m-f-t** [comment] 2017-02-23 16:31
@QuarantineENG, there's not enough information in what you've provided to really troubleshoot this.

If you would like, you may send me what you have at cameron.dixon@hq.dhs.gov and I can take a look.

**Comment by QuarantineENG** [comment] 2017-02-24 08:55
Will do

**Comment by QuarantineENG** [comment] 2017-03-03 12:06
This is still dead in the water. I have tried the following listed below;

install gcc libffi-devel python-devel and openssl-devel
pip install cryptography
pip install requests[security]

re-ran pshtt - received error below still

Traceback (most recent call last):
  File "/usr/bin/pshtt", line 9, in <module>
    load_entry_point('pshtt==0.1.5', 'console_scripts', 'pshtt')()
  File "/usr/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 882, in inspect_domains
    results.append(inspect(domain))
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 63, in inspect
    basic_check(domain.https)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 173, in basic_check
    https_check(endpoint)
  File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 331, in https_check
    cert_plugin_result = cert_plugin.process_task(server_info, 'certinfo_basic')
  File "/usr/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 115, in process_task
    if scan_command.custom_ca_file:
AttributeError: 'str' object has no attribute 'custom_ca_file'

**Comment by h-m-f-t** [comment] 2017-03-10 16:18
Closing for now. @QuarantineENG indicated offline that the Fedora environment he's been provided may have him hamstrung at the moment. pshtt ought to work in RHEL variants, though I've not personally tested.

**Comment by QuarantineENG** [comment] 2017-03-24 11:13
I have installed it on Debian with the following;
fresh install of debian 8
apt-get update
apt-get upgrade
python -V
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
apt-get install gcc*
apt-get upgrade
reboot -n
apt-get install build-essential libssl-dev libffi-dev python-dev
pip install pshtt
pip install deptree

 pshtt===0.15
   docopt 0.6.2
   request 2.13.0
   requests-cache 0.4.13
     requests 2.13.0
   sslyze 1.0.0
     enum34 1.1.6
     nassl 0.15.1
       enum34 1.1.6
       typing 3.5.3.0
     typing 3.5.3.0
   wget 3.2

 It is still throwing errors. I sent over the email to Cameron this morning.  This time it starts with line 15 instead of line 9.

traceback (most recent call last):
 File "/usr/local/bin/pshtt", line 11 <modle>
 sys.exit(main())
File "/usr/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
results = pshtt.inspect_domains(domains, options)
File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 882, in inspect_domains
results.append(inspect(domain))
File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 63, in inspect
basic_check(domain.https)
File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 173, in basic_check
https_check(endpoint)
File "/usr/lib/python2.7/site-packages/pshtt/pshtt.py", line 331, in https_check
cert_plugin_result = cert_plugin.process_task(server_info, 'certinfo_basic')
File "/usr/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 115, in process_task
if scan_command.custom_ca_file:
AttributeError: 'str' object has no attribute 'custom_ca_file'

**Comment by h-m-f-t** [comment] 2017-04-13 19:36
Had several people report `AttributeError: 'str' object has no attribute 'custom_ca_file'`, who aren't intending to specify a custom_ca_file. Reopening.

**Comment by mmclean636jr** [comment] 2017-04-13 20:41
Can you please point me to a solution or workaround for this?
 
I'm assuming that the prescribed instance needs a custom CA input but how/where should I begin?
 
**https@ubuntu:~/PSHTT_Tool/RESULTS$ pshtt -d ahu.ndc.nasa.gov**
Fetching Chrome preload list from source...
Starting new HTTPS connection (1): chromium.googlesource.com
https://chromium.googlesource.com:443 "GET /chromium/src/net/+/master/http/transport_security_state_static.json?format=TEXT HTTP/1.1" 200 None
Fetching Chrome pending preload list...
Starting new HTTPS connection (1): hstspreload.org
https://hstspreload.org:443 "GET /api/v2/pending HTTP/1.1" 200 375051
pinging http://ahu.ndc.nasa.gov...
Starting new HTTP connection (1): ahu.ndc.nasa.gov
Failed to connect.
pinging http://www.ahu.ndc.nasa.gov...
Starting new HTTP connection (1): www.ahu.ndc.nasa.gov
Failed to connect.
pinging https://ahu.ndc.nasa.gov...
Starting new HTTPS connection (1): ahu.ndc.nasa.gov
Starting new HTTPS connection (1): ahu.ndc.nasa.gov
https://ahu.ndc.nasa.gov:443 "GET / HTTP/1.1" 200 2574
sslyzing https://ahu.ndc.nasa.gov...
Traceback (most recent call last):
  File "/home/https/.local/bin/pshtt", line 11, in <module>
    sys.exit(main())
  File "/home/https/.local/lib/python2.7/site-packages/pshtt/cli.py", line 54, in main
    results = pshtt.inspect_domains(domains, options)
  File "/home/https/.local/lib/python2.7/site-packages/pshtt/pshtt.py", line 882, in inspect_domains
    results.append(inspect(domain))
  File "/home/https/.local/lib/python2.7/site-packages/pshtt/pshtt.py", line 63, in inspect
    basic_check(domain.https)
  File "/home/https/.local/lib/python2.7/site-packages/pshtt/pshtt.py", line 173, in basic_check
    https_check(endpoint)
  File "/home/https/.local/lib/python2.7/site-packages/pshtt/pshtt.py", line 331, in https_check
    cert_plugin_result = cert_plugin.process_task(server_info, 'certinfo_basic')
  File "/home/https/.local/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 115, in process_task
    if scan_command.custom_ca_file:
_AttributeError: 'str' object has no attribute 'custom_ca_file'_
**https@ubuntu:~/PSHTT_Tool/RESULTS$**

**Comment by h-m-f-t** [comment] 2017-07-21 06:19
I'm pretty certain this was when the requirements.txt was pulling in the latest versions of sslyze but pshtt wasn't following the changed syntax (this was predominantly fixed via #74). I can longer recreate this issue.

**Closed by h-m-f-t** 2017-07-21 06:19 UTC
